#!/usr/bin/env python3
import json

# Colors
RESET = '\033[0m'; BOLD = '\033[1m'; DIM = '\033[2m'
RED = '\033[38;5;203m'; GREEN = '\033[38;5;83m'; YELLOW = '\033[38;5;220m'
CYAN = '\033[38;5;51m'; MAGENTA = '\033[38;5;213m'; BLUE = '\033[38;5;75m'
WHITE = '\033[97m'; ORANGE = '\033[38;5;208m'; PURPLE = '\033[38;5;141m'

def box_top():    print(f"{CYAN}╔{'═'*76}╗{RESET}")
def box_bot():    print(f"{CYAN}╚{'═'*76}╝{RESET}")
def box_line(s):  print(f"{CYAN}║{RESET} {s}")
def sep():        print(f"{DIM}{CYAN}{'─'*78}{RESET}")

files = {
    "🛡️  NIST CYBERSECURITY FRAMEWORK 2.0": ("/home/ubuntu/edr-compliance-reports/EDR-NIST_CSF-20260815.json", GREEN),
    "💳 PCI-DSS v4.0": ("/home/ubuntu/edr-compliance-reports/EDR-PCI_DSS-20260815.json", ORANGE),
    "🔐 ISO/IEC 27001:2022": ("/home/ubuntu/edr-compliance-reports/EDR-ISO27001-20260815.json", PURPLE),
}

print(f"\n{BOLD}{WHITE}")
print("   ██╗  ██╗███████╗ █████╗ ██╗  ████████╗██╗  ██╗ ██████╗ █████╗ ██████╗ ███████╗")
print("   ██║  ██║██╔════╝██╔══██╗██║  ╚══██╔══╝██║  ██║██╔════╝██╔══██╗██╔══██╗██╔════╝")
print("   ███████║█████╗  ███████║██║     ██║   ███████║██║     ███████║██████╔╝█████╗  ")
print("   ██╔══██║██╔══╝  ██╔══██║██║     ██║   ██╔══██║██║     ██╔══██║██╔══██╗██╔══╝  ")
print("   ██║  ██║███████╗██║  ██║███████╗██║   ██║  ██║╚██████╗██║  ██║██║  ██║███████╗")
print("   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝   ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝")
print(f"{RESET}{DIM}          IoMT EDR Platform · Automated Compliance Engine{RESET}\n")

for title, (path, color) in files.items():
    with open(path) as f:
        d = json.load(f)

    box_top()
    box_line(f"{BOLD}{color}{title}{RESET}")
    box_bot()

    print(f"   {YELLOW}📅 Period{RESET}      {d['period_start']}  →  {d['period_end']}")
    print(f"   {YELLOW}🕒 Generated{RESET}   {d['generated_at'][:19].replace('T',' ')} UTC")
    score = d['compliance_score']
    bar = '█' * (score // 5) + '░' * (20 - score // 5)
    print(f"   {YELLOW}🎯 Score{RESET}       {GREEN}{bar}{RESET} {BOLD}{GREEN}{score}%{RESET}")

    print(f"\n   {MAGENTA}{BOLD}📊 KEY METRICS{RESET}")
    s = d['statistics']
    print(f"      📦 Total Events           {WHITE}{BOLD}{s['total_events']:>6}{RESET}")
    print(f"      🔴 Critical Alerts        {RED}{BOLD}{s['critical_alerts']:>6}{RESET}")
    print(f"      🟠 High Alerts            {ORANGE}{BOLD}{s['high_alerts']:>6}{RESET}")
    print(f"      🟢 Auto-Contained         {GREEN}{BOLD}{s['auto_contained']:>6}{RESET}")
    print(f"      ⏱️  MTTD (Mean Detect)     {CYAN}{s['mttd_minutes']:>6} min{RESET}")
    print(f"      ⏱️  MTTR (Mean Respond)    {CYAN}{s['mttr_minutes']:>6} min{RESET}")
    print(f"      📡 Agents Monitored       {BLUE}{BOLD}{s['agents_monitored']:>6}{RESET}")
    print(f"      ✅ Uptime                 {GREEN}{BOLD}{s['uptime_percent']:>6}%{RESET}")
    print(f"      ⚠️  False Positive Rate    {YELLOW}{s['false_positive_pct']:>6}%{RESET}")

    print(f"\n   {MAGENTA}{BOLD}✅ CONTROLS VERIFIED{RESET}")
    for name, c in d['controls'].items():
        print(f"      {GREEN}✔{RESET} {BOLD}{WHITE}{name}{RESET}  {DIM}[{c['status']}]{RESET}")
        print(f"        {DIM}└─ {c['evidence'][:95]}{RESET}")

    print()
    sep()
    print()

print(f"{BOLD}{GREEN}   ✏️  Auto-generated by AI-Driven Healthcare IoMT EDR Platform{RESET}")
print(f"{DIM}      Kainat Zahra Khalil · EduQual Level 6 Diploma in AI Operations{RESET}\n")
