search {
  index = cortex
  uri = "http://172.31.33.186:9200"
}

analyzer {
  urls = [
    "https://catalogs.download.strangebee.com/latest/json/analyzers.json",
    "/opt/cortex-analyzers/analyzers"
  ]
}

responder {
  urls = [
    "https://catalogs.download.strangebee.com/latest/json/responders.json"
  ]
}
