#!/usr/bin/env python3
import subprocess, glob, os, sys, re

RESET = '\033[0m'; BOLD = '\033[1m'; DIM = '\033[2m'
RED = '\033[38;5;203m'; GREEN = '\033[38;5;83m'; YELLOW = '\033[38;5;220m'
CYAN = '\033[38;5;51m'; MAGENTA = '\033[38;5;213m'; BLUE = '\033[38;5;75m'
WHITE = '\033[97m'; ORANGE = '\033[38;5;208m'

def sep(): print(f"{DIM}{CYAN}{'─'*78}{RESET}")

reports = sorted(glob.glob(os.path.expanduser("~/forensics-tools/reports/report_*.html")), reverse=True)
if not reports:
    print("No forensic reports found.")
    sys.exit(1)
path = reports[0]

raw = subprocess.run(["lynx", "-dump", "-nolist", path], capture_output=True, text=True).stdout
lines = raw.split("\n")

print(f"\n{BOLD}{WHITE}")
print("   🔬  F O R E N S I C   A N A L Y S I S   R E P O R T")
print(f"{RESET}{DIM}      Healthcare IoMT EDR · TShark + Volatility3 Pipeline{RESET}\n")
sep()

# Header info
for l in lines[:5]:
    if "Capture:" in l:
        print(f"   {YELLOW}📎 Capture{RESET}     {WHITE}{l.split('Capture:')[1].split('🕒')[0].strip()}{RESET}")
    if "Generated:" in l:
        gen = l.split("Generated:")[1].split("🆔")[0].strip()
        print(f"   {YELLOW}🕒 Generated{RESET}   {gen}")
sep()

# Threat indicators
idx = next((i for i,l in enumerate(lines) if "Threat Indicators" in l), None)
if idx is not None:
    print(f"\n   {RED}{BOLD}⚠️  THREAT INDICATORS{RESET}")
    for l in lines[idx+1:idx+6]:
        l = l.strip()
        if not l: continue
        if l.startswith("HIGH") or l.startswith("MEDIUM") or l.startswith("LOW") or l.startswith("INFO"):
            sev = l.split()[0]
            msg = l[len(sev):].strip()
            color = RED if sev=="HIGH" else ORANGE if sev=="MEDIUM" else YELLOW if sev=="LOW" else DIM
            print(f"      {color}{BOLD}[{sev}]{RESET} {msg[:95]}")
        if "Traffic Overview" in l:
            break

# Traffic overview numbers
idx = next((i for i,l in enumerate(lines) if "Traffic Overview" in l), None)
if idx is not None:
    print(f"\n   {MAGENTA}{BOLD}📊 TRAFFIC OVERVIEW{RESET}")
    block = [x.strip() for x in lines[idx+1:idx+12] if x.strip()]
    icons = {"IP Conversations":"🔗","DNS Queries":"🔎","HTTP Requests":"🌍","Memory Snapshot":"🧠"}
    i = 0
    while i < len(block)-1:
        val, label = block[i], block[i+1]
        if label in icons:
            print(f"      {icons[label]} {label:<20} {CYAN}{BOLD}{val}{RESET}")
            i += 2
        else:
            i += 1

# Protocol hierarchy
idx = next((i for i,l in enumerate(lines) if "frame " in l and "frames:" in l), None)
if idx is not None:
    print(f"\n   {MAGENTA}{BOLD}🌐 PROTOCOL BREAKDOWN{RESET}")
    for l in lines[idx:idx+15]:
        if "frames:" in l:
            print(f"      {GREEN}▸{RESET} {l.strip()}")
        elif "====" in l or not l.strip():
            break

# IP Conversations
idx = next((i for i,l in enumerate(lines) if "<->" in l), None)
if idx is not None:
    print(f"\n   {MAGENTA}{BOLD}💬 TOP IP CONVERSATIONS{RESET}")
    count = 0
    for l in lines[idx:]:
        if "<->" in l:
            print(f"      {BLUE}⇄{RESET} {l.strip()[:95]}")
            count += 1
            if count >= 6: break

print()
sep()
print(f"\n   {GREEN}{BOLD}✏️  Healthcare-Extended EDR · Automated Forensic Pipeline{RESET}")
print(f"{DIM}      Kainat Zahra Khalil · Generated by TShark + Volatility3{RESET}\n")
