#!/usr/bin/env python3
"""
IoMT-EDR Auto Investigation Report
Automatically generated when a TheHive Case is created (CRITICAL / HIGH).
"""

import os
import json
import datetime
from pathlib import Path

REPORT_DIR = Path("investigation_reports")
REPORT_DIR.mkdir(exist_ok=True)

def generate_report(case_id=None, device_id="unknown", device_type="IoMT Device",
                    rule_description="Security event", severity="CRITICAL",
                    wazuh_alert_id=None, flow_id=None, extra_notes=""):

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_id = (case_id or "auto").replace("/", "_")[:30]

    # Velociraptor summary (confirmed evidence)
    vr_section = ""
    if flow_id:
        vr_section = f"""
FORENSIC COLLECTION (Velociraptor)
----------------------------------
Flow ID        : {flow_id}
Client ID      : C.4dbc16cd0ca01939
Status         : FINISHED
Total Evidence : 153 rows collected

What was collected:
  • System Information     → 21 rows
  • Running Processes      → 123 rows
  • Network Connections    → 8 rows  (most important for zone violations)

Evidence location: velociraptor://C.4dbc16cd0ca01939/{flow_id}
"""

    report = f"""
================================================================================
                    IoMT-EDR INVESTIGATION REPORT
================================================================================

Report Generated : {now}
Case ID          : {case_id or "Auto-generated"}
Severity         : {severity}
Device           : {device_id} ({device_type})
Alert Rule       : {rule_description}
Wazuh Alert ID   : {wazuh_alert_id or "N/A"}

--------------------------------------------------------------------------------
1. WHAT HAPPENED
--------------------------------------------------------------------------------
A {severity} security event was detected on a medical/IoMT device.
The system automatically:
  • Created a case in TheHive for investigation
  • Evaluated network containment
  • Collected live forensic evidence from the device

--------------------------------------------------------------------------------
2. PATIENT SAFETY IMPACT
--------------------------------------------------------------------------------
• This event may involve unauthorized communication (zone violation).
• Device was still online when evidence was collected.
• Process list and network connections have been preserved for review.
• Clinical engineering should be informed if this is a life-supporting device.

{vr_section}
--------------------------------------------------------------------------------
3. CHAIN OF CUSTODY
--------------------------------------------------------------------------------
Forensic collection was automatically logged when the case was created.
Full chain-of-custody records are maintained in chain_of_custody.jsonl.

--------------------------------------------------------------------------------
4. RECOMMENDED ACTIONS
--------------------------------------------------------------------------------
1. Review the TheHive case and confirm containment status.
2. Check whether the device tried to communicate outside its allowed network zone.
3. Update the device risk score if this is a repeated incident.
4. Escalate to clinical engineering if patient safety is at risk.

--------------------------------------------------------------------------------
5. NOTES
--------------------------------------------------------------------------------
{extra_notes or "No additional notes."}

================================================================================
Generated by IoMT-EDR platform | Manager: 172.31.44.154 | Forensics: 172.31.33.186
================================================================================
"""

    txt_path = REPORT_DIR / f"investigation_{safe_id}_{ts}.txt"
    txt_path.write_text(report.strip())

    # Simple clean HTML version
    html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Investigation Report - {safe_id}</title>
<style>
body{{font-family:system-ui,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;line-height:1.5}}
h1{{color:#b91c1c;border-bottom:3px solid #b91c1c}}
.badge{{background:#fee2e2;color:#991b1b;padding:3px 12px;border-radius:20px;font-weight:bold}}
pre{{background:#f8fafc;padding:16px;border-radius:8px;white-space:pre-wrap}}
</style></head>
<body>
<h1>IoMT-EDR Investigation Report</h1>
<p><span class="badge">{severity}</span> &nbsp; Generated: {now}</p>
<pre>{report}</pre>
</body></html>"""

    html_path = REPORT_DIR / f"investigation_{safe_id}_{ts}.html"
    html_path.write_text(html)

    print(f"[REPORT] Saved: {txt_path}")
    return str(txt_path)


if __name__ == "__main__":
    generate_report(
        device_id="C.4dbc16cd0ca01939",
        device_type="Linux IoMT endpoint",
        rule_description="Zone violation / Patient Safety",
        severity="CRITICAL",
        flow_id="F.D9UQR2IFDFFRU",
        extra_notes="Demo / test report"
    )
